### ISSUE TITLE
Feature request: switch device On or Off

### ISSUE THREAD

**Issue by guussie** [doctorfree/RoonCommandLine#2]
In the Roon app, I can switch my Devialet Expert On or Off with, without starting play.

Is it possible to make these commands available for the command line?

Especially the Off command is useful in a home automation context.

**Comment by doctorfree** [comment]
@guussie thanks for opening a feature request. Let me first make sure I understand what you are asking for.

By "On" and "Off" are you referring to enabling and disabling an audio device or unmuting/muting a device?

RoonCommandLine does not perform any device configuration but it can be used to mute and unmute configured Roon zones. I am going to guess you wish to also be able to mute and unmute individual audio devices within a zone. Is that correct?

Control of individual audio device volume from the command line is a good feature to add to RoonCommandLine. Currently you could do that if the device were the only device in a zone. I think I can add this feature but it will take some work which will take some time. That is, I believe it is possible.

Is individual device volume control what you are after? If not, could you clarify for me the feature you request? Thankjs.

**Comment by JSonnabend** [comment]
The Python library exposes the necessary functionality, but I can't see a
way to do it as a command line tool.  You need some code that keeps the web
socket open to receive the event notification.

**Comment by guussie** [comment]
> The Python library exposes the necessary functionality, but I can't see a way to do it as a command line tool. You need some code that keeps the web socket open to receive the event notification.
> […](#)

That's interesting. I will look into this. Perhaps I can launch the functionality through the execution of a Python script.

Thanks!

**Comment by hanwalt** [comment]
Hello,
I would like to have this feature, too.

Correct me when I am wrong but the standby / power feature is part of the [RoonApiTransport](https://roonlabs.github.io/node-roon-api/RoonApiTransport.html)

-> Convenience switch

<head></head><h4 class="name" id="convenience_switch" style="font-style: normal; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; font-weight: 200; margin: 0px 0px 12px; font-size: 18px; letter-spacing: -0.33px; color: rgb(77, 78, 83); font-family: Consolas, Monaco, &quot;Andale Mono&quot;, monospace; caret-color: rgb(77, 78, 83);">convenience_switch<span class="signature" style="font-family: Consolas, Monaco, &quot;Andale Mono&quot;, monospace;">(output, opts, cb<span class="signature-attributes" style="font-size: 10.8px; color: rgb(170, 170, 170); font-style: italic; font-weight: lighter;">opt</span>)</span><span class="type-signature" style="color: rgb(170, 170, 170);"></span></h4><div class="description" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin-bottom: 1em; margin-top: 1em; caret-color: rgb(77, 78, 83); color: rgb(77, 78, 83); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;">Cconvenience switch an output, taking it out of standby if needed.</div><h5 style="font-style: normal; font-variant-caps: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; font-size: 16.799999px; font-weight: bold; letter-spacing: -0.01em; margin: 8px 0px 3px; caret-color: rgb(77, 78, 83); color: rgb(77, 78, 83); font-family: &quot;Open Sans&quot;, sans-serif;">Parameters:</h5>
Name | Type | Attributes | Description
-- | -- | -- | --
output | Output |   | The output that should be convenience-switched.
opts | object |   | Options. If none, specify empty object ({}).PropertiesNameTypeAttributesDescriptioncontrol_keystring<optional>The control_key that identifies the source_controlthat is to be switched. If omitted, then all controls on this output will be convenience switched. | control_key | string | <optional> | The control_key that identifies the source_controlthat is to be switched. If omitted, then all controls on this output will be convenience switched.

control_key | string | <optional> | The control_key that identifies the source_controlthat is to be switched. If omitted, then all controls on this output will be convenience switched.
cb | RoonApiTransport~resultcallback | <optional> | Called on success or error

<dl class="details" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; margin-bottom: 40px; margin-top: 14px; border-left-width: 2px; border-left-style: solid; border-left-color: rgb(221, 221, 221); caret-color: rgb(77, 78, 83); color: rgb(77, 78, 83); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px;"><dt class="tag-source" style="width: 120px; float: left; padding-left: 10px; padding-top: 6px;">Source:</dt><dd class="tag-source" style="margin-left: 70px;"><ul class="dummy" style="margin: 0px; list-style-type: none;"><li style="margin-left: 30px; padding-top: 6px;"><a href="https://roonlabs.github.io/node-roon-api/other_node-roon-api-transport_lib.js.html" style="color: rgb(0, 149, 221); text-decoration: none;">other/node-roon-api-transport/lib.js</a>,<span class="Apple-converted-space"> </span><a href="https://roonlabs.github.io/node-roon-api/other_node-roon-api-transport_lib.js.html#line164" style="color: rgb(0, 149, 221); text-decoration: none;">line 164</a></li></ul></dd></dl>convenience_switch(output, opts, cbopt)

Cconvenience switch an output, taking it out of standby if needed.
Parameters:
Name	Type	Attributes	Description
output	[Output](https://roonlabs.github.io/node-roon-api/Output.html)		The output that should be convenience-switched.
opts	object		Options. If none, specify empty object ({}).
Properties
Name	Type	Attributes	Description
control_key	string	<optional>
The control_key that identifies the source_control that is to be switched. If omitted, then all controls on this output will be convenience switched.
cb	RoonApiTransport~resultcallback	<optional>
Called on success or error
Source:
[other/node-roon-api-transport/lib.js](https://roonlabs.github.io/node-roon-api/other_node-roon-api-transport_lib.js.html), [line 164](https://roonlabs.github.io/node-roon-api/other_node-roon-api-transport_lib.js.html#line164)

**Comment by hanwalt** [comment]
I see that your project is based on Python Roon API that is why I raised an update feature there.
