### ISSUE TITLE
Feature Request: Move Audio from One Zone to Another

### ISSUE THREAD

**Issue by mrnoisytiger** [doctorfree/RoonCommandLine#4]
I am frequently needing to move the currently playing audio from one zone to another zone. For example, I move from my headphones to speakers setup routine, and Roon's Zone Switching allows me to do that without losing any of my queue or play status. 

There was a forum post that enlightened me to this feature [here](https://community.roonlabs.com/t/how-do-i-switch-zones-solved/11119).

**Comment by doctorfree** [comment]
This is a good feature request. I want that too! I'm adding this to my to-do list for the next release.

**Comment by doctorfree** [comment]
@mrnoisytiger I've created a new release which primarily contains support for transferring the current queue to another zone. See https://github.com/doctorfree/RoonCommandLine/releases/tag/v2.1.0r4

This release includes the new command `transfer_zone` which takes an optional first argument specifying the source zone and a second argument specifying the destination zone name. If no source zone is specified then the first argument is the destination zone. For example, to transfer the current queue from the current active zone to the zone "WiiM Pro Plus" you would enter the command:

```bash
transfer_zone "WiiM Pro Plus"
```

To transfer from zone "HomePod Max" to "WiiM Pro Plus" you would enter:

```bash
transfer_zone "HomePod Max" "WiiM Pro Plus"
```

The `roon` command can also be used to perform the transfer, acting as a front-end for `transfer_zone`:

```bash
roon -F "HomePod Max" -D "WiiM Pro Plus"
```

where `-F` specifies the source zone and `-D` specifies the destination zone. If no `-F` is provided then the last played zone is used as the source.

No menu support for this feature exists as yet.

If you try it out let me know how it goes. As you can see, this was fairly quickly implemented so it has little test time.

**Comment by mrnoisytiger** [comment]
@doctorfree Amazing! Just played around a couple of times from Zones with displays to DAC's and Google Homes and HomePods, and it worked flawlessly. 

So much snappier than doing it through the UI. Thank you!

**Comment by mrnoisytiger** [comment]
I'm actually planning on using this to integrate into [RayCast](https://www.raycast.com/) through an extension! So, CLI makes the most sense overall. I always spend so much time in shell screwing around with servers anyways.
